services:
  genggam-makna-api:
    image: "vinssdroid/genggam-makna-backend-api:v1"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genggam-makna-backend-api
    env_file:
      - /etc/secrets/genggam-makna-backend-api.env
    ports:
      - "8002:8002"
    networks:
      - nginx-mailcow-host
    volumes:
      - /etc/secrets:/etc/secrets
    command:
      ["./genggam-makna-backend-api"]

networks:
  nginx-mailcow-host:
    external: true